import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// CHANGELOG.md is generated by semantic-release from the commit bodies, verbatim
// and unescaped. So a commit body is Markdown whether its author meant it to be,
// and one shape leaks: a line that STARTS with `#`.
//
// Writing "fixes #24" at the start of a line, or a bare `#` as a separator, puts
// an H1 into the middle of a release entry. From then on the document has two
// kinds of H1 — release headings and whatever that line said — and every tool
// that reads the changelog by its headings (the GitHub release body, a docs
// site, a reader scrolling) sees a release that does not exist.
//
// Nothing is broken today. This is the ratchet that keeps it that way, and it
// fails on the commit that would introduce it rather than on the release.

const CHANGELOG = readFileSync(join(import.meta.dirname, "..", "CHANGELOG.md"), "utf8");

/**
 * The document's title, and a release heading as semantic-release writes it:
 * `# [1.39.0](https://github.com/…) (date)` for every release with a
 * predecessor, and a bare `# 1.0.0 (date)` for the first one, which has nothing
 * to compare against.
 */
const TITLE = /^# Changelog$/;
const RELEASE = /^#{1,3} (?:\[\d+\.\d+\.\d+]\(https:\/\/github\.com\/|\d+\.\d+\.\d+ \(\d{4}-\d{2}-\d{2}\)$)/;

describe("CHANGELOG.md structure survives the commit bodies it is built from", () => {
  it("has exactly one title", () => {
    const titles = CHANGELOG.split("\n").filter((l) => TITLE.test(l));
    expect(titles).toHaveLength(1);
  });

  it("contains no H1 that is not the title or a release heading", () => {
    const stray = CHANGELOG.split("\n")
      .map((line, i) => ({ line, n: i + 1 }))
      .filter(({ line }) => /^# /.test(line) || line.trimEnd() === "#")
      .filter(({ line }) => !TITLE.test(line) && !RELEASE.test(line));

    expect(
      stray.map(({ line, n }) => `${n}: ${line}`),
      "a line starting with `#` in a commit body becomes an H1 in the changelog — " +
        "write `issue 24` or `n°24` rather than `#24` at the start of a line, and never a bare `#`",
    ).toEqual([]);
  });

  it("has no heading deeper than a release's own subsections", () => {
    // semantic-release emits `### Bug Fixes` / `### Features` and nothing deeper.
    // An `####` can only have come out of a commit body.
    const deep = CHANGELOG.split("\n")
      .map((line, i) => ({ line, n: i + 1 }))
      .filter(({ line }) => /^#{4,} /.test(line));
    expect(deep.map(({ line, n }) => `${n}: ${line}`)).toEqual([]);
  });
});
